1151 shell to specific instance - part 1 - list application instances
epinio/epinio pull request #1171
Opened 2022-02-01 14:16 UTC by jimmykarily

This is a preparation for #1151

We first need a way to list application instances. Then the user can request a shell to a specific instance.
This PR changes the endpoint for `epinio app show`, to list the application instances with their metrics.

2022-02-01 14:52 UTC, jimmykarily commented on internal/application/workload.go
> +	// Calculate metrics
Unnecessary comment, will remove
```suggestion
```

2022-02-02 07:16 UTC, jimmykarily commented on acceptance/api/v1/application_show_test.go
> +		for _, v := range appObj.Workload.Replicas {
I realize now that we use the terms `Replica`, `Pod` and `Instance` in various places and we refer to the same thing. I will change it to be `Instance` everywhere (as in "application instance")

2022-02-03 10:13 UTC, andreas-kupries requested changes
Looks ok to me, although the test `lists the application data [It]` got broken. Apparently the closing `Eventually` does not happen.

2022-02-03 10:28 UTC, jimmykarily commented
> Looks ok to me, although the test `lists the application data [It]` got broken. Apparently the closing `Eventually` does not happen.

I'll run that test locally to ensure it's passing. If yes, I will increase the 4s timeout to 15s. Maybe the "Restarts" field didn't have enough time to update itself?

2022-02-03 10:50 UTC, jimmykarily commented
> > Looks ok to me, although the test `lists the application data [It]` got broken. Apparently the closing `Eventually` does not happen.
> 
> I'll run that test locally to ensure it's passing. If yes, I will increase the 4s timeout to 15s. Maybe the "Restarts" field didn't have enough time to update itself?

Test passes locally, I increased the timeout and rebased the branch to origin/main

2022-02-03 11:32 UTC, andreas-kupries approved these changes

2022-02-03 12:52 UTC, merged