Reduce epinio docker image size
epinio/epinio pull request #1211
Opened 2022-02-14 08:12 UTC by thardeck

We use `FROM scratch` instead of OpenSUSE as base for epinio-server. The image size is reduced from 236MB in v0.4.0 to 47MB.

scratch does not provide a readable write dir so we provide one via
volume mount.

This does have the advantage that we properly split the tmp dir from the
node.
The tmp dir is needed to pull an app from git.

The remaining penalty of scratch is that we can not shell into it
easily, but there are workarounds for it which we can document.

Fixes #1145

2022-02-16 09:16 UTC, manno requested changes

2022-02-16 09:16 UTC, manno commented on scripts/prepare-environment-k3d.sh
> +k3d image import -c epinio-acceptance splatform/epinio-server:latest
Please let's not use splatform anymore

2022-02-17 09:33 UTC, thardeck commented
This pr requires https://github.com/epinio/helm-charts/pull/103 to be merged.

2022-02-17 15:19 UTC, andreas-kupries approved these changes

2022-02-17 15:36 UTC, merged