Hide password from show command
epinio/epinio pull request #1499
Opened 2022-05-30 12:01 UTC by enrichman

Ref:
- #1361 
---

This PR will hide the password from the `epinio settings show` command.

It can be shown specifying the `--show-password` flag.

2022-05-30 12:11 UTC, andreas-kupries submitted a review, later dismissed
Looks ok. Also looks to be in conflict with the new table matchers

2022-05-30 12:12 UTC, enrichman commented
@andreas-kupries that's correct, that's why I asked for the review of that one! Now that is merged I'll rebase it and resolve the conflicts. :+1:

2022-05-31 06:37 UTC, jimmykarily commented
Can we maybe hash the password in the `settings.yaml` file too? Just in case someone is editing the file while someone else is looking. Could happen on another PR.

2022-05-31 09:00 UTC, andreas-kupries requested changes
Looks good. The change request is for checking and updating the epinio [docs](https://github.com/epinio/docs) around adding and removing users.

2022-06-01 06:58 UTC, enrichman commented
I'm going to update doc about users in a separate PR (lots of thing moving around auth and users these days), and I will address the password encoding in another one as well.

2022-06-01 06:58 UTC, merged