Allow to override default application port
epinio/epinio pull request #2150
Opened 2023-03-21 15:15 UTC by giubacc

The port is pushed inside the application container via the environment variable: PORT.
The value defaults to 8080; it can be specified using a custom chart value during the application's push:

epinio push -n 'app-name' --chart-value 'appListeningPort=8087'

Addresses: #1792
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

2023-03-22 08:39 UTC, enrichman requested changes
To test this you need to open a matching PR on the `helm-charts` repository with the required changes (the `0.1.25-rc1` chart, and the other things), and update the submodules of this one.

If those are ok we can bump the application chart to a stable release, removing the `-rc1` suffix before merging them.

Do we want to enable even lower port values? What if the standard `80` or `443` ports are needed?

2023-03-22 08:49 UTC, giubacc commented
> To test this you need to open a matching PR on the `helm-charts` repository with the required changes (the `0.1.25-rc1` chart, and the other things), and update the submodules of this one.
> 
> If those are ok we can bump the application chart to a stable release, removing the `-rc1` suffix before merging them.
> 

ok

> Do we want to enable even lower port values? What if the standard `80` or `443` ports are needed?

Initially I thought this could be the right thing to do, but then I thought that could be uncommon opening a well-known-port directly on a pod.
On the other hand, it is true that you couldn't have the control on which port you can open on your application (even I find it hard to think of a real case).
I dunno.. @andreas-kupries  what do you think?

2023-03-27 13:36 UTC, enrichman approved these changes

2023-03-27 13:37 UTC, merged

2023-04-26 15:16 UTC, thehejik commented
Verified fixed in `v1.8.0-rc1`
- over Web UI deployed a simple py http server app listening on port 1234 - entered AppListeningPort = 1234
- ingress endpoint forwards to the app pod correctly and the app works
![image](https://user-images.githubusercontent.com/12828077/234620488-443bbff1-f2f4-4c8e-b105-31a4554b4d8b.png)


The app:
```
cat index.html
<H1>Hello World</H1>
---
cat Procfile
web: python server.py
---
cat server.py
#!/usr/bin/env python3 -u
import http.server
import socketserver

PORT = 1234

Handler = http.server.SimpleHTTPRequestHandler

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("serving at port", PORT)
    httpd.serve_forever()
---
```