Fixed same suggestions for multiple resources
epinio/epinio pull request #2249
Opened 2023-04-27 15:03 UTC by enrichman

The `epinio app env set` command was not using the common `matchingAppsFinder` func.

Also some app/service/config commands (`delete`) accepts more than one resource, but our completion were suggesting also the already added resources.

A common `filteredMatchingFinder` func is used.

2023-04-28 07:30 UTC, andreas-kupries requested changes
Leftover variable names indicating start of the generic finder as an app name finder.

2023-04-28 07:30 UTC, andreas-kupries commented on internal/cli/commons.go
> +	alreadyMatchedApps := map[string]struct{}{}
```suggestion
	alreadyMatched := map[string]struct{}{}
```

Given that this is a generic finder `App` makes no sense.

2023-04-28 07:30 UTC, andreas-kupries commented on internal/cli/commons.go
> +	alreadyMatchedApps := map[string]struct{}{}
This change will induce updating the other places.

2023-04-28 07:30 UTC, andreas-kupries commented on internal/cli/commons.go
> +		// return only the not matched apps
```suggestion
		// return only the not already matched arguments
```

2023-04-28 07:30 UTC, andreas-kupries commented on internal/cli/commons.go
> +	for _, app := range matches {
```suggestion
	for _, resource := range matches {
```

2023-05-03 08:37 UTC, andreas-kupries approved these changes

2023-05-03 08:57 UTC, merged

2023-05-25 13:14 UTC, mmartin24 commented
Checked in `v1.8.1-rc1` 
No duplications after autosugestions:
After `epinio configuration delete config-1 config-2` and pressing tab, does not duplicate config-1