Better error message for a missing setting.yaml file
epinio/epinio pull request #2502
Opened 2023-08-02 08:22 UTC by andreas-kupries

Fix #2467

2023-08-02 13:28 UTC, enrichman requested changes
This is not checking for the existance of the settings file but for the API url to be set. Still fine to have it, but this will prevent the user from understanding if it's using a non-existing file or just a settings file with the url not set.

We already have this check [here](https://github.com/epinio/epinio/blob/main/internal/cli/settings/settings.go#L99-L102), but it seems it doesn't work: 

```go
settingsExists, err := fileExists(file)
if err != nil {
	return nil, errors.Wrapf(err, "filesystem error")
}
```

Maybe [this](https://github.com/epinio/epinio/blob/main/internal/cli/settings/settings.go#L84) is preventing the check?

```go
v.SetConfigFile(file)
```

2023-08-02 13:55 UTC, andreas-kupries commented
> This is not checking for the existence of the settings file but for the API url to be set.

Yes, intentionally.

> ... will prevent the user from understanding if it's using a non-existing file or just a settings file with the url not set.

I do not see the user caring about this distinction.
The result of either is the same, failure to talk to the E API server.
The solution is the same too, logging into the desired E API endpoint.

I believe that the solution is good as-is.

2023-08-02 14:06 UTC, enrichman commented
Actually I opened the issue because one of the bug that we have found was probably not catched because of this.
Also if in the code the check exists but is not triggered that means that there is a flaw in the logic and a bug that we should fix. Basically why the `fileExists` doesn't work?

There are also different scenarios where the information is useful. I'm thinking about the `epinio` cli running on a CI, and having this error for a typo in the epinio settings location. It will be very hard or difficult to understand why it's not working, while having a "settings not found" will be much easier to understand.

2023-08-02 14:18 UTC, andreas-kupries commented
> We already have this check [here](https://github.com/epinio/epinio/blob/main/internal/cli/settings/settings.go#L99-L102), but it seems it doesn't work:
> Maybe [this](https://github.com/epinio/epinio/blob/main/internal/cli/settings/settings.go#L84) is preventing the check?

No. This tells viper where to look for the file. This is independent of the other check

I rather suspect that the error from `LoadFrom` is simply ignored by some caller.

Ok, will have another look and see if a working file check can be added.

2023-08-03 11:31 UTC, enrichman commented
Just a small comment, but it's ok. I can approve it right after the small change (if agreed), then CI should be fine!

2023-08-03 11:32 UTC, andreas-kupries commented on internal/cli/usercmd/login.go
> +	epinioSettings.Location = "fake"
Ok

2023-08-03 11:35 UTC, andreas-kupries commented on internal/cli/usercmd/login.go
> +	epinioSettings.Location = "fake"
Wwll, not quite. The helper used by the caller ... Looks good enough.

2023-08-03 11:39 UTC, andreas-kupries commented on internal/cli/usercmd/login.go
> +	epinioSettings.Location = "fake"
Looking a bit more I believe that your request will break OIDC mode of `login`.
That has no `updateSettings`, just `verifyCredentials`.
The config is directly set up, would need a copy of the Location code.
Having it in `verify...` keeps it DRY.

2023-08-03 11:39 UTC, andreas-kupries commented on internal/cli/usercmd/login.go
> +	epinioSettings.Location = "fake"
I decline to make the change.

2023-08-03 11:40 UTC, enrichman approved these changes

2023-08-03 11:42 UTC, merged