fix: use networking.k8s.io/v1 Ingress instead of extensions/v1beta1
epinio/epinio pull request #258
Opened 2021-04-06 18:06 UTC by kkaempf

Removes warnings like
> W0402 10:55:31.309809   17207 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

Fixes #172

2021-04-07 04:32 UTC, rohitsakala requested changes
Are we not caring about kube clusters <1.18 now ? [0]

[0] https://github.com/SUSE/carrier/blob/main/kubernetes/cluster.go#L513

2021-04-07 10:58 UTC, kkaempf commented
> Are we not caring about kube clusters <1.18 now ?

I wouldn't care about <1.18, see [here](https://github.com/SUSE/carrier/issues/172#issuecomment-814815835) for the arguments.

2021-04-07 12:00 UTC, kkaempf commented
Hmm, 1.18.17 also has problems with `networking/v1` :thinking:

2021-04-14 14:35 UTC, manno commented
> networks.k8s.io/v1 was introduced in Kubernetes v1.15+, the Ingress resource was promoted to v1 only in Kubernetes v1.19+

So, we need to bump the requirement to 1.19 to use v1.


However, with the way versioning works in k8s (stored version, served version), you can use any version to read it: 

> When you create an ingress object, it can be read via any version (the server handles converting into the requested version).  (https://github.com/kubernetes/kubernetes/issues/94761#issuecomment-691982480)

2021-05-04 08:21 UTC, jimmykarily commented
The end goal is for the epinio cli to only talk to the epinio server and not to the Kube api directly. That means, any warnings will only appear on the epinio server pod and the user won't see them. I'm closing this.

2021-05-04 08:21 UTC, closed without merging

2021-05-05 07:29 UTC, jimmykarily commented
For as long as we still support <=1.18 : https://github.com/epinio/epinio/pull/354