Improve tests
epinio/epinio pull request #428
Opened 2021-05-27 14:29 UTC by jimmykarily

Follow up of  #402 to address remaining PR comments.

2021-05-27 14:32 UTC, jimmykarily commented
TODO: One more comment to address: https://github.com/epinio/epinio/pull/402#issuecomment-849529793

2021-05-27 14:40 UTC, andreas-kupries requested changes
Saw only two things, `defer`s which should be `AfterEach` instead.

2021-05-27 14:40 UTC, andreas-kupries commented on acceptance/api_v1_applications_test.go
> +				defer deleteApp(app)
This should be an `AfterEach`, should it not ?

2021-05-27 14:40 UTC, andreas-kupries commented on acceptance/api_v1_applications_test.go
> +				existingLogs := readLogs(org, app)
Ditto above, the `defer` can go if we use `AfterEach`.

2021-05-28 07:08 UTC, jimmykarily commented
> Saw only two things, `defer`s which should be `AfterEach` instead.

It's golang's responsibility to run deferred functions while AfterEach is provided by Ginkgo. I felt more confident that it would always run if it was a defer (e.g panics etc). By reading Ginkgo docs, I think it's fine to move it to AfterEach. Will do.

2021-05-28 09:06 UTC, andreas-kupries requested changes
I rewrote the explanations to use a more active voice.
Tried for shorter sentence too.

2021-05-28 09:06 UTC, andreas-kupries commented on internal/api/v1/applications.go
> +	// Send logs coming to logChan over to websockets connection until either
```suggestion
	// Send logs received on logChan to the websockets connection until either
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// There are 2 ways this method can be stopped:
```suggestion
// There are 2 ways of stopping this method:
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 1. If the connection is closed
```suggestion
// 1. The websocket connection closes.
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 2. If something is sent to the interrupt channel
```suggestion
// 2. Something is sent to the interrupt channel
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// - the go routines closes the connection on interrupt. This causes the main
```suggestion
// - The go routines closes the connection on interrupt. This causes the main
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// - the main thread sends a signal to the `done` channel when it returns. This
```suggestion
// - The main thread sends a signal to the `done` channel when it returns. This
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 1. the go routine closes the connection
```suggestion
// 1. The go routine closes the connection
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 2. the loop in the main thread is stopped because the connection was closed
```suggestion
// 2. The loop in the main thread is stopped because the connection was closed
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 3. the main thread sends to the `done` chan (as a "defer" function), it then
```suggestion
// 3. The main thread sends to the `done` chan (as a "defer" function), and then
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 4. the go routine receives the `done` message, calls wg.Done() and returns
```suggestion
// 4. The go routine receives the `done` message, calls wg.Done() and returns
```

2021-05-28 09:06 UTC, andreas-kupries commented on internal/cli/clients/client.go
> +// 5. the main thread returns
```suggestion
// 5. The main thread returns
```

2021-05-28 11:30 UTC, andreas-kupries approved these changes

2021-05-28 11:56 UTC, merged