Add create app to CLI and fix delete
epinio/epinio pull request #553
Opened 2021-06-28 13:37 UTC by manno

With the new apps create command, it was also necessary to fix apps delete, so it can delete apps that don't have a workload.

fixes #515

2021-06-28 16:50 UTC, manno commented
CI is flaky:

```
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-create Saving epinio-registry.192.168.64.3.omg.howdoi.website/apps/apps-932472169-53bbef6aade4515f83cfabf17a27e08385a868fa... 
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-create *** Images (sha256:056d7052ff8b4e5f9ab26e46758386e955a57d71730d1ff45dd7bad68432864b): 
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-create       epinio-registry.192.168.64.3.omg.howdoi.website/apps/apps-932472169-53bbef6aade4515f83cfabf17a27e08385a868fa - GET https://epinio-registry.192.168.64.3.omg.howdoi.website/v2/: unexpected status code 404 Not Found: 404 page not found 
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-create  
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-create ERROR: failed to export: failed to write image to the following tags: [epinio-registry.192.168.64.3.omg.howdoi.website/apps/apps-932472169-53bbef6aade4515f83cfabf17a27e08385a868fa: GET https://epinio-registry.192.168.64.3.omg.howdoi.website/v2/: unexpected status code 404 Not Found: 404 page not found 
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-create ] 
[7]       🕞  [5fd97cf3c5fd3120-stage-b6vgw-pod-78jtx] step-results 2021/06/28 15:21:32 Skipping step because a previous step failed 
[7]       error pushing app to server: waiting for staging failed: Tasks Completed: 2 (Failed: 1, Cancelled 0), Skipped: 2
[7]       
[7]       Unexpected error:
[7]           <*exec.ExitError | 0xc00007c000>: {
[7]               ProcessState: {
[7]                   pid: 12079,
[7]                   status: 65280,
[7]                   rusage: {
[7]                       Utime: {Sec: 0, Usec: 288747},
[7]                       Stime: {Sec: 0, Usec: 28401},
[7]                       Maxrss: 43724,
[7]                       Ixrss: 0,
[7]                       Idrss: 0,
[7]                       Isrss: 0,
[7]                       Minflt: 2421,
[7]                       Majflt: 0,
[7]                       Nswap: 0,
[7]                       Inblock: 0,
[7]                       Oublock: 136,
[7]                       Msgsnd: 0,
[7]                       Msgrcv: 0,
[7]                       Nsignals: 0,
[7]                       Nvcsw: 7451,
[7]                       Nivcsw: 76,
[7]                   },
[7]               },
[7]               Stderr: nil,
[7]           }
[7]           exit status 255
[7]       occurred
[7] 
[7]       /home/carrier/action-runner/_work/epinio/epinio/acceptance/utilities_test.go:101
```


```
[2]     🚢 Create Service
[2]     Name: service-560912905
[2]     Organization: orgs-560911555
[2]     Class: mariadb
[2]     Plan: 10-3-22
[2]     | PARAMETER | VALUE |
[2]     |-----------|-------|
[2]     
[2]     🚢 Provisioning................................................................................................................................................................................................................................................................................................................error creating service: Internal Server Error: {"errors":[{"status":500,"title":"timed out waiting for the condition","details":""}]}
[2]     
[2]     
[2]     Unexpected error:
[2]         <*exec.ExitError | 0xc000806000>: {
[2]             ProcessState: {
[2]                 pid: 24959,
[2]                 status: 65280,
[2]                 rusage: {
[2]                     Utime: {Sec: 0, Usec: 93496},
[2]                     Stime: {Sec: 0, Usec: 27702},
[2]                     Maxrss: 47296,
[2]                     Ixrss: 0,
[2]                     Idrss: 0,
[2]                     Isrss: 0,
[2]                     Minflt: 1553,
[2]                     Majflt: 0,
[2]                     Nswap: 0,
[2]                     Inblock: 0,
[2]                     Oublock: 0,
[2]                     Msgsnd: 0,
[2]                     Msgrcv: 0,
[2]                     Nsignals: 0,
[2]                     Nvcsw: 3788,
[2]                     Nivcsw: 22,
[2]                 },
[2]             },
[2]             Stderr: nil,
[2]         }
[2]         exit status 255
[2]     occurred
[2] 
[2]     /home/carrier/action-runner/_work/epinio/epinio/acceptance/catalog_services_test.go:47
```

2021-06-29 07:12 UTC, andreas-kupries requested changes
Some nits in comment so far.

2021-06-29 07:12 UTC, andreas-kupries commented on internal/application/application.go
> +// List returns an list of all available workloads (in the org)
```suggestion
// List returns a list of all available workloads (in the org)
```
Absolutely a nit.

2021-06-29 07:12 UTC, andreas-kupries commented on internal/cli/clients/apps_create.go
> +// currently targeted kube cluster
`AppCreate` has nothing to do with credentials and config.

2021-06-29 07:22 UTC, andreas-kupries commented
Ok, as you fixed `app delete` I suspect that fixing `app list` will be in scope also.

```
work@tagetarl:~/SUSE/dev/epinio> ep app list 

🚢 Listing applications
Organization: workspace

✔️  Epinio Applications:
| NAME | STATUS | ROUTES | SERVICES |
|------|--------|--------|----------|
```

This is after `ep app create hello` was run successfully.

2021-06-29 07:24 UTC, andreas-kupries commented
I wonder if that cross over into #536 territory

2021-06-29 07:28 UTC, andreas-kupries commented
And with the empty app present push fails also. Considers the apps to exist.

```
work@tagetarl:~/SUSE/dev/epinio> ep app push hello assets/sample-app

🚢 About to push an application with given name and sources into the specified organization
Name: hello
Sources: assets/sample-app
Organization: workspace

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)


Create the application resource ...
error pushing app to server: Internal Server Error: {"errors":[{"status":500,"title":"applications.app.k8s.io \"hello\" already exists","details":""}]}
```

After deleting the lone resource it is ok to push again.

Side note, back to `app list` ... Related to that command is the match function for argument completion.

2021-06-29 08:25 UTC, manno commented
> Ok, as you fixed `app delete` I suspect that fixing `app list` will be in scope also.

This is actually a separate story: #510 
I had to fix delete to make the test green. Then I had so much context on deletion that I also tried to fix the "deleting incomplete deployments" problem. 

> And with the empty app present push fails also. Considers the app to exist at a point where it does not consider updating as solution

Good catch. That should have been in the acceptance criteria. This feature doesn't make sense without being able to push.

2021-07-01 08:48 UTC, andreas-kupries approved these changes
Found a nit around the cli help for this command. Approved anyway, can be fixed at leisure, should not delay merge of the functionality itself.

2021-07-01 08:48 UTC, andreas-kupries commented on internal/cli/apps.go
> +	SilenceUsage:  true,
This should be adapted to the changes in the other commands, i.e. `Silence*: false` by default, and `SilenceUsage` dynamically activated in the command function. See PR #539 . This is something which can be done after this is merged. I.e. a nit, and I do not wish to cause more delay.

2021-07-01 08:54 UTC, merged