Update all epinio docs for SLC
epinio/epinio pull request #571
Opened 2021-07-01 14:58 UTC by rohitsakala

fixes #377

2021-07-02 08:06 UTC, andreas-kupries requested changes

2021-07-02 08:06 UTC, andreas-kupries commented on README.md
> +- Service mesh integration and testing
I believe that this section should clarify that this is __not__ a proper roadmap, and just themes and things we consider possible.

2021-07-02 09:16 UTC, andreas-kupries commented on README.md
> +- Service mesh integration and testing
Done with commit f84f601a8bc5c8f10cdb44581e2d6a09ade37fbb

2021-07-07 07:48 UTC, viccuad commented
(the doc structure was recommended to us by @mattfarina :)

2021-07-12 08:58 UTC, andreas-kupries approved these changes

2021-07-13 07:42 UTC, merged