856 full index dont fail
epinio/epinio pull request #860
Opened 2021-10-04 10:52 UTC by jimmykarily

Fixes #856

2021-10-04 11:03 UTC, jimmykarily commented
I can't say I'm very satisfied with this solution but I can't come up with something better right now. Also not sure how to test this. I would need to either force the race condition or force an app to get an error some other way.

The `fetch` is the only function that sets the new `Error` field I introduced. If something constructs the app object using another method, this field won't be set. An empty `Error` field, anywhere in the code flow, should mean there is no error. Right now it could also mean, nobody run the function that sets it.
This happens because there is no "standard" way enforced on how to get an app object. You can have an app object that never went through the `fetch` method or one that did. And there is no way to tell unless you follow the code.

Maybe this is ok, but I feel this makes the code hard to follow and could lead to bugs. I'm trying to think where the origin of the problem lies and what needs to be refactored. Any ideas, welcome.

2021-10-05 12:20 UTC, jimmykarily commented
I think #774 and #856 could be solved in one go. If there is an error while populating the application's fields, we can just set the application status to "error". In the case of the app being deleted behind the scenes, this "error" state will be transient. Ideally there should be no error and the app should not be returned but delete actions in kubernetes are not instant. We could introduce a "deleting" state but it will be hard to calculate that state.

2021-10-05 12:36 UTC, jimmykarily commented on internal/api/v1/stage.go
> +	client := cs.TektonV1beta1().PipelineRuns(deployments.TektonStagingNamespace)
Use this when merged? https://github.com/epinio/epinio/pull/862/files#diff-e02c24d0a09d47ddaca26d2c3540697e3dae4ce4f296b3f7448c6f34dc6dfc12R198

2021-10-05 12:36 UTC, jimmykarily commented on internal/application/application.go
> +	client := cs.TektonV1beta1().PipelineRuns(deployments.TektonStagingNamespace)
here too? https://github.com/epinio/epinio/pull/862/files#diff-e02c24d0a09d47ddaca26d2c3540697e3dae4ce4f296b3f7448c6f34dc6dfc12R198

2021-10-05 12:42 UTC, jimmykarily commented
I opened the PR for a first review. If we like the solution I will add some tests for it (in a very non TDD way).

2021-10-05 13:06 UTC, andreas-kupries requested changes

2021-10-05 13:06 UTC, andreas-kupries commented on internal/application/application.go
> +// To decide what the status value should be it combined various pieces of information.
```suggestion
// To decide what the status value should be it combines various pieces of information.
```

2021-10-05 13:49 UTC, manno commented on internal/application/application.go
> +// To decide what the status value should be it combined various pieces of information.
```suggestion
// To decide what the status value should be, it combines various pieces of information.
```

2021-10-06 07:19 UTC, andreas-kupries approved these changes

2021-10-06 12:05 UTC, merged