Implement --env parameter for push and apps create/update
epinio/epinio pull request #861
Opened 2021-10-04 11:49 UTC by thardeck

Fixes #643

2021-10-04 11:55 UTC, andreas-kupries requested changes

2021-10-04 11:55 UTC, andreas-kupries commented on internal/cli/options.go
> +	// - AppUpdate API will treat it as no op, i.e. keep current instances.
The three preceding comment lines are about the instances, not services, nor EV. Should be moved up to where the instances are handled in this function

2021-10-04 13:58 UTC, kkaempf commented on internal/cli/options.go
> +			return result, errors.New("Bad --env assignment, expected `name=value` as value")
Maybe add the `assignment` value to the error message to show which `--env` assignment is meant here ?!

2021-10-06 08:16 UTC, andreas-kupries approved these changes

2021-10-06 08:16 UTC, merged